repos:
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: |
          (?x)^(
            .*\.lock|
            .*lock\.yml|
            uv\.lock|
            dbt_airbnb_case/package-lock\.yml|
            dbt_airbnb_case/target/.*|
            dbt_airbnb_case/dbt_packages/.*|
            dbt_airbnb_case/logs/.*
          )$